title: "Blog Title"
author: "Michael Tu"
description: "Really cool blog about ... something"
more: "read more »"
url: "https://michatu.github.io/"
baseurl: "/contrast"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/michaeltu1"
  - envelope: "mailto:mtu@berkeley.edu"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
